service: web-scraper

frameworkVersion: '2'

custom: 
  jobsTopicName: ${self:service}-${self:provider.stage}-jobs
  jobsTopicArn:
    Fn::Join:
      - ""
      - - "arn:aws:sns:"
        - ${self:provider.region}
        - ":"
        - Ref: AWS::AccountId
        - ":"
        - ${self:custom.jobsTopicName}
  crawlsTableName: ${self:service}-${self:provider.stage}-crawls
  crawlsTableArn: 
    Fn::Join:
      - ":"
      - - arn
        - aws
        - dynamodb
        - Ref: AWS::Region
        - Ref: AWS::AccountId
        - "table/${self:custom.crawlsTableName}"  
  
provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-2
  environment:
    CRAWLS_TABLE_NAME: ${self:custom.crawlsTableName}
    SNS_JOBS_TOPIC_ARN: ${self:custom.jobsTopicArn}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - sns:Publish
      Resource:
        - ${self:custom.jobsTopicArn}
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:PutItem
        - dynamodb:UpdateItem
      Resource:
        - ${self:custom.crawlsTableArn}
   
resources:
  Resources:
    CrawlsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.crawlsTableName}
        ProvisionedThroughput:
          ReadCapacityUnits: 2
          WriteCapacityUnits: 2
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: scrapeId
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
          - AttributeName: scrapeId
            KeyType: RANGE
  
functions:
  scrape:
    handler: functions/scrape.run
    events:
      - http:
          path: scrapes
          method: post
          cors: true
      - sns: ${self:custom.jobsTopicName}
  crawl:
    handler: functions/crawl.run
    events:
      - http:
          path: crawls
          method: post
          cors: true
  view:
    handler: functions/view.run
    events:
      - http:
          path: crawls/{id}
          method: get
          cors: true

