
service: serverless-crud

frameworkVersion: '2'

plugins:
  - serverless-finch

custom:
  snippetsTableName: ${self:service}-${self:provider.stage}-snippets
  snippetsTableArn: 
    Fn::Join:
      - ":"
      - - arn
        - aws
        - dynamodb
        - Ref: AWS::Region
        - Ref: AWS::AccountId
        - table/${self:custom.snippetsTableName}
  client:
    bucketName: ${self:service}-${self:provider.stage}-snippets-site

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-2
  environment:
    SNIPPETS_TABLE_NAME: ${self:custom.snippetsTableName}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Get*
        - dynamodb:BatchGet*
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - dynamodb:Scan
      Resource:
        - ${self:custom.snippetsTableArn}

resources:
  Resources:
    SnippetsTableName:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.snippetsTableName}
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
            
functions:
  createSnippet:
    handler: functions/createSnippet.handler
    events:
      - http:
          path: snippets
          method: post
          cors: true
  getSnippets:
    handler: functions/getSnippets.handler
    events:
      - http:
          path: snippets
          method: get
          cors: true
  getSnippet:
    handler: functions/getSnippet.handler
    events:
      - http:
          path: snippets/{id}
          method: get
          cors: true
  updateSnippet:
    handler: functions/updateSnippet.handler
    events:
      - http:
          path: snippets/{id}
          method: patch
          cors: true
  deleteSnippet:
    handler: functions/deleteSnippet.handler
    events:
      - http:
          path: snippets/{id}
          method: delete
          cors: true